<?php
define('SECURITY_SALT', 'myb0t2quvt2q7q2m');

// Session
const SESS_USER_ID = 'SESS_USER_ID';
const SESS_LOGIN_EXPIRE_TIME = 'SESS_LOGIN_EXPIRE_TIME';
const SESS_RESIST_STATUS = 'SESS_RESIST_STATUS';
const SESS_RESIST_DATA = 'SESS_RESIST_DATA';
const SESS_RESIST_USER_DATA = 'SESS_RESIST_USER_DATA';
const SESS_ERROR_MESSAGE = 'SESS_ERROR_MESSAGE';
const SESS_TEACHER_REGISTER_CHECK_KEY = 'SESS_TEACHER_REGISTER_CHECK_KEY';

// Cookie
define('COOKIE_AUTH_KEY', 'AuthKey');

// Directory
define('ROOT_DIR', dirname(__DIR__));
define('SYS_DIR', __DIR__);
define('COMMON_DIR', SYS_DIR. '/Commons');
define('MODEL_DIR', SYS_DIR . '/Models');
define('CONTROLLER_DIR', SYS_DIR . '/Controllers');
define('LOG_DIR', SYS_DIR . '/Logs');
define('TEMP_DIR', SYS_DIR . '/Temps');

// Log
define('ERROR_LOG_FILE', 'error.log');
define('LOG_TYPE_LOGIN', 1);
define('LOG_TYPE_LOGOUT', 2);
define('LOG_TYPE_IS_LOGIN_WITH_GET_AUTH', 3);
define('LOG_TYPE_FOLDER_COPY_PRE_PROCESS', 101);
define('LOG_TYPE_FOLDER_COPY', 102);
define('LOG_TYPE_CREATE_TEST_AUTO', 201);
define('LOG_TYPE_CREATE_TEST_MANUAL', 301);
define('LOG_TYPE_ACCESS_TOP', 901);
define('LOG_TYPE_GAS', 1001);

// Form Type
const TYPE_PAGE_BREAK_ITEM = "page_break_item";

const TYPE_QUESTION_GROUP                   = 'question_group';
const TYPE_CALCULATED_QUESTION              = 'calculated_question';
const TYPE_ESSAY_QUESTION                   = 'essay_question';
const TYPE_FILE_UPLOAD_QUESTION             = 'file_upload_question';
const TYPE_FILL_IN_MULTIPLE_BLANKS_QUESTION = 'fill_in_multiple_blanks_question';
const TYPE_MATCHING_QUESTION                = 'matching_question';
const TYPE_MULTIPLE_ANSWERS_QUESTION        = 'multiple_answers_question';
const TYPE_MULTIPLE_CHOICE_QUESTION         = 'multiple_choice_question';
const TYPE_MULTIPLE_DROPDOWNS_QUESTION      = 'multiple_dropdowns_question';
const TYPE_NUMERICAL_QUESTION               = 'numerical_question';
const TYPE_SHORT_ANSWER_QUESTION            = 'short_answer_question';
const TYPE_TEXT_ONLY_QUESTION               = 'text_only_question';
const TYPE_TRUE_FALSE_QUESTION              = 'true_false_question';

const TYPE_VERTICAL_QUESTION_GROUP                   = 'vertical_question_group';
const TYPE_VERTICAL_CALCULATED_QUESTION              = 'vertical_calculated_question';
const TYPE_VERTICAL_ESSAY_QUESTION                   = 'vertical_essay_question';
const TYPE_VERTICAL_FILE_UPLOAD_QUESTION             = 'vertical_file_upload_question';
const TYPE_VERTICAL_FILL_IN_MULTIPLE_BLANKS_QUESTION = 'vertical_fill_in_multiple_blanks_question';
const TYPE_VERTICAL_MATCHING_QUESTION                = 'vertical_matching_question';
const TYPE_VERTICAL_MULTIPLE_ANSWERS_QUESTION        = 'vertical_multiple_answers_question';
const TYPE_VERTICAL_MULTIPLE_CHOICE_QUESTION         = 'vertical_multiple_choice_question';
const TYPE_VERTICAL_MULTIPLE_DROPDOWNS_QUESTION      = 'vertical_multiple_dropdowns_question';
const TYPE_VERTICAL_NUMERICAL_QUESTION               = 'vertical_numerical_question';
const TYPE_VERTICAL_SHORT_ANSWER_QUESTION            = 'vertical_short_answer_question';
const TYPE_VERTICAL_TEXT_ONLY_QUESTION               = 'vertical_text_only_question';
const TYPE_VERTICAL_TRUE_FALSE_QUESTION              = 'vertical_true_false_question';

// Form Type GAS
define('GAS_TYPE_CHECKBOX_GRID_ITEM', 1);
define('GAS_TYPE_CHECKBOX_ITEM', 2);
define('GAS_TYPE_DATE_ITEM', 3);
define('GAS_TYPE_DATE_TIME_ITEM', 4);
define('GAS_TYPE_DURATION_ITEM', 5);
define('GAS_TYPE_GRID_ITEM', 6);
define('GAS_TYPE_IMAGE_ITEM', 7);
define('GAS_TYPE_LIST_ITEM', 8);
define('GAS_TYPE_MULTIPLE_CHOICE_ITEM', 9);
define('GAS_TYPE_PAGE_BREAK_ITEM', 10);
define('GAS_TYPE_PARAGRAPH_TEXT_ITEM', 11);
define('GAS_TYPE_SCALE_ITEM', 12);
define('GAS_TYPE_SECTION_HEADER_ITEM', 13);
define('GAS_TYPE_TEXT_ITEM', 14);
define('GAS_TYPE_TIME_ITEM', 15);
define('GAS_TYPE_VIDEO_ITEM', 16);
define('GAS_TYPE_TEXT_ITEM_NO_POINTS', 21);

// Book
define('FLAG_ENGLISH_BOOK', 0);
define('FLAG_JAPANESE_BOOK', 1);

// User
define('USER_STATUS_ACTIVE', 0);
define('USER_STATUS_DELETED', 99);

// Browser
define('BROWSER_UNKNOWN', 0);
define('BROWSER_MICROSOFT_EDGE', 1);
define('BROWSER_MICROSOFT_INTERNET_EXPLORER', 2);
define('BROWSER_OPERA', 3);
define('BROWSER_GOOGLE_CHROME', 4);
define('BROWSER_FIREFOX', 5);
define('BROWSER_SAFARI', 6);

// Regist Status
define('REGISTER_STATUS_NONE', 0);
define('REGISTER_STATUS_REGISTERED', 1);
define('REGISTER_STATUS_UPDATED', 2);
define('REGISTER_STATUS_DELETED', 3);
define('REGISTER_STATUS_SKIP', 4);
define('REGISTER_STATUS_SKIP_WITHOUT_LOGIN_ID', 5);
define('REGISTER_STATUS_SKIP_WITHOUT_SCHOOL_ID', 6);

// Login
define('LOGIN_FAILED_LIMIT', 5);
define('LOGIN_FAILED_LIMIT_INTERVAL', 300); // 5分

// GAS
define('GAS_URL_SWITCH_THRESHOLD', 100);

// Admin
//define('ADMIN_LOGIN_ID', 'ILAdmin');
//define('ADMIN_LOGIN_PW', 'Bwe0vm98_f9v8m2qy2093c');
define('SESS_ADMIN_LOGIN_TIME', 'SESS_ADMIN_LOGIN_TIME');

const PAGE_LIMIT = 50;

const REGISTRATION_KEY_STATUS_REGISTERED = 1;
const REGISTRATION_KEY_STATUS_DISABLED = 2;

// Error
define('ERROR_NONE', 0);
define('ERROR_LOGIN_FAILED', 1);
define('ERROR_LOGIN_BLOCK_IP', 2);
define('ERROR_LOGIN_LIMIT_IP', 3);
define('ERROR_LOGIN_LIMIT_USER_ID', 4);
//define('ERROR_CREATE_PROCESS_KEY', 101);
//define('ERROR_LACK_OF_TOTAL', 102);
//define('ERROR_INVALID_TOTAL', 103);
//define('ERROR_NO_DAIMON_DATA', 104);
//define('ERROR_NO_CHAPTER_DATA', 105);
//define('ERROR_NO_MIDASI_DATA', 106);
//define('ERROR_INVALED_PARAMETERS', 107);
define('ERROR_UNKNOWN_DRIVE_ID', 1001);
define('ERROR_GAS_NOT_FOUND_GAS_URL', 2001);
define('ERROR_AUTH_EXPIRED', 9001);
define('ERROR_AUTH_INCORRECT_KEY', 9002);

const ERROR_REGISTRATION_KEY_NOT_FOUND           = 1101;
const ERROR_REGISTRATION_KEY_ALREADY_REGISTERED  = 1102;
const ERROR_REGISTRATION_KEY_DISABLED            = 1103;
const ERROR_REGISTRATION_KEY_FAILED              = 1104;
const ERROR_REGISTRATION_KEY_ALREADY_HAVING_BOOK = 1105;

// Error for Admin
define('ERROR_ADMIN_USER_ADD_FAILED', 10001);
define('ERROR_ADMIN_USER_UPDATE_FAILED', 10002);
define('ERROR_ADMIN_USER_DELETE_FAILED', 10003);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_INVALID', 10004);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_NOT_SET_LOGIN_ID', 10005);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_NOT_SET_PASSWORD', 10006);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_NOT_SET_PREF', 10007);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_NOT_SET_SCHOOL', 10008);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_NOT_SET_SCH_ZIP', 10009);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_NOT_SET_SCH_ADD', 10010);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_NOT_SET_SCH_PHONE', 10011);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_NOT_SET_NAME_SEI', 10012);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_NOT_SET_NAME_MEI', 10013);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_NOT_SET_KANA_SEI', 10014);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_NOT_SET_KANA_MEI', 10015);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_NOT_SET_MAIL', 10016);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_NOT_SET_GACCOUNT', 10017);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_REGISTERED_LOGIN_ID', 10022);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_PASSWORD_NOT_SAME', 10023);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_MAIL_INVALID', 10050);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_PHONE_INVALID', 10051);
define('ERROR_ADMIN_USER_REGISTER_PARAMETER_ZIP_INVALID', 10052);
define('ERROR_ADMIN_USER_REGISTER_NOT_CHECK_PRIVACY', 10053);
define('ERROR_ADMIN_USER_REGISTER_NOT_CHECK_TERMS', 10054);
define('ERROR_ADMIN_UPLOAD_FILE_FAILED', 10091);
define('ERROR_ADMIN_UPLOAD_FILE_NOT_CSV', 10092);

define('ERROR_ADMIN_REGISTRATION_ADD_FAILED', 10101);
define('ERROR_ADMIN_REGISTRATION_UPDATE_FAILED', 10102);
define('ERROR_ADMIN_REGISTRATION_DELETE_FAILED', 10103);
define('ERROR_ADMIN_REGISTRATION_REGISTER_PARAMETER_INVALID', 10104);

// Error for Json Quiz
const ERROR_JSON_QUIZ_ADD_FAILED = 10201;
const ERROR_JSON_QUIZ_GET_LAST_INSERT_ID_FAILED = 10202;
const ERROR_JSON_QUIZ_INVALID_URL = 10301;
const ERROR_JSON_QUIZ_PERMISSION = 10302;
const ERROR_JSON_QUIZ_NOT_RELEASE_OR_PERMISSION = 10303;
const ERROR_JSON_QUIZ_NO_DATA = 10304;
const ERROR_JSON_QUIZ_RESULT_INVALID_PARAMETER = 10401;
const ERROR_JSON_QUIZ_RESULT_ADD_FAILED = 10402;
const ERROR_JSON_QUIZ_RESULT_UPDATE_JSON_QUIZ = 10403;

const ERROR_JSON_QUIZ_RESULT_SEND_THRESHOLD = 5;

define('ERROR_UNKNOWN', 99999);

// Manual Mdde
define('CHANGE_DISPLAY_TYPE_NOT_SET', 0);
define('CHANGE_DISPLAY_TYPE_QUESTION', 1);
define('CHANGE_DISPLAY_TYPE_LEVEL', 2);