<?php

namespace IizunaLMS\Errors;

use IizunaLMS\Helpers\DisplayJsonHelper;

class Error
{
    const ERROR_NONE = 0;
    const ERROR_NOT_LOGIN = 1000;
    const ERROR_LOGIN_FAILED = 1001;
    const ERROR_LOGIN_BLOCK_IP = 1002;
    const ERROR_LOGIN_LIMIT_IP = 1003;
    const ERROR_TEACHER_INVALID_PARAMETERS = 1101;
    const ERROR_TEACHER_REGISTERED_LOGIN_ID = 1102;
    const ERROR_TEACHER_GET_LAST_INSERT_ID = 1103;
    const ERROR_SCHOOL_REGISTER_FAILED = 1201;
    const ERROR_SCHOOL_REGISTER_FAILED_EBOOK_STATUS = 1202;
    const ERROR_SCHOOL_GROUP_REGISTER_FAILED = 1301;
    const ERROR_SCHOOL_GROUP_PARAMETER_ERROR = 1302;
    const ERROR_SCHOOL_GROUP_DATA_IS_NONE = 1303;
    const ERROR_QR_PARAMETER_ERROR = 1401;
    const ERROR_QUIZ_DELIVERY_REGISTER_FAILED = 1501;
    const ERROR_QUIZ_DELIVERY_PARAMETER_ERROR = 1502;
    const ERROR_QUIZ_DELIVERY_DATA_IS_NONE = 1503;
    const ERROR_QUIZ_PREVIEW_NO_DATA = 1504;
    const ERROR_QUIZ_PREVIEW_PERMISSION = 1505;
    const ERROR_QUIZ_PUSH_NOTIFICATION_FAILED = 1506;
    const ERROR_ONIGIRI_LEARNING_RANGE_PARAMETER_ERROR = 1601;
    const ERROR_STUDENT_CODE_REGISTER_FAILED = 1701;
    const ERROR_STUDENT_CODE_PARAMETER_ERROR = 1702;
    const ERROR_STUDENT_CODE_DELETE_FAILED = 1703;
    const ERROR_ONIGIRI_QUIZ_ACCESS_DENIED = 1800;
    const ERROR_ONIGIRI_QUIZ_PARAMETER_ERROR = 1801;
    const ERROR_ONIGIRI_QUIZ_PARAMETER_EMPTY_STAGE = 1802;
    const ERROR_ONIGIRI_QUIZ_PARAMETER_EMPTY_TOTAL = 1803;
    const ERROR_ONIGIRI_QUIZ_PARAMETER_TOTAL_MIN = 1804;
    const ERROR_ONIGIRI_QUIZ_PARAMETER_TOTAL_MAX = 1805;
    const ERROR_ONIGIRI_QUIZ_PARAMETER_EMPTY_LMS_CODE = 1806;
    const ERROR_ONIGIRI_QUIZ_PARAMETER_EMPTY_TITLE = 1807;
    const ERROR_ONIGIRI_QUIZ_PARAMETER_EMPTY_TYPE = 1808;
    const ERROR_ONIGIRI_QUIZ_PARAMETER_INVALID_TERMS = 1809;
    const ERROR_ONIGIRI_QUIZ_RECORD_FAILED = 1810;
    const ERROR_ONIGIRI_QUIZ_DELETE_FAILED = 1811;
    const ERROR_ONIGIRI_QUIZ_DELETE_INVALID_PARAMETER = 1812;
    const ERROR_ONIGIRI_QUIZ_DELETE_NOT_FOUND = 1813;
    const ERROR_ONIGIRI_QUIZ_DELETE_NOT_PERMIT = 1814;
    const ERROR_ONIGIRI_JSON_QUIZ_INVALID_URL = 1815;
    const ERROR_ONIGIRI_JSON_QUIZ_NO_DATA = 1816;
    const ERROR_ONIGIRI_QUIZ_DELIVERY_REGISTER_FAILED = 1817;
    const ERROR_ONIGIRI_QUIZ_DELIVERY_PARAMETER_ERROR = 1818;
    const ERROR_ONIGIRI_QUIZ_DELIVERY_DATA_IS_NONE = 1819;
    const ERROR_ONIGIRI_QUIZ_DELIVERY_NOTIFICATION_FAILER = 1820;
    const ERROR_ONIGIRI_QUIZ_DELIVERY_NOTIFICATION_ID_NOT_FOUND = 1821;
    const ERROR_ONIGIRI_QUIZ_DELIVERY_NOTIFICATION_ID_REGIST_FAILER = 1822;
    const ERROR_ONIGIRI_QUIZ_DELIVERY_UPDATE_FAILED = 1823;
    const ERROR_ONIGIRI_JSON_QUIZ_RESULT_INVALID_PARAMETER = 1824;
    const ERROR_ONIGIRI_JSON_QUIZ_RESULT_ADD_FAILED = 1825;
    const ERROR_ONIGIRI_JSON_QUIZ_RESULT_UPDATE_JSON_QUIZ = 1826;
    const ERROR_ONIGIRI_JSON_QUIZ_STUDENT_RESULT_ACCESS_ERROR = 1827;
    const ERROR_ONIGIRI_JSON_QUIZ_RESULT_PERMISSION = 1828;
    const ERROR_ONIGIRI_JSON_QUIZ_PREVIEW_NO_DATA = 1829;
    const ERROR_ONIGIRI_JSON_QUIZ_PREVIEW_PERMISSION = 1830;
    const ERROR_ONIGIRI_QUIZ_CHOICE_GET_PROBLEMS_PARAMETER_ERROR = 1831;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_PARAMETER_ERROR = 1832;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_REGISTER_FAILED = 1833;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_CANNOT_PARENT_OWN = 1834;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_CANNOT_PARENT_DESCENDANTS = 1835;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_DELETE_INVALID_PARAMETER = 1836;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_DELETE_NOT_FOUND = 1837;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_DELETE_NOT_PERMIT = 1838;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_DELETE_FAILED = 1839;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_DELETE_REMAIN_CHILD = 1840;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_MOVE_QUIZ_INVALID_PARAMETER = 1841;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_MOVE_QUIZ_FAILED = 1842;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_MOVE_NOT_PERMIT = 1843;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_MOVE_NOT_FOUND = 1844;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_BULK_MOVE_QUIZ_INVALID_PARAMETER = 1845;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_BULK_MOVE_QUIZ_FAILED = 1846;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_BULK_MOVE_NOT_PERMIT = 1847;
    const ERROR_ONIGIRI_JSON_QUIZ_FOLDER_BULK_MOVE_NOT_FOUND = 1848;
    const ERROR_BOOK_APPLICATION_PARAMETER_ERROR = 1900;
    const ERROR_BOOK_APPLICATION_REGISTER_FAILED = 1901;
    const ERROR_BOOK_APPLICATION_DELETE_FAILED = 1902;
    const ERROR_AUTH_EXPIRED = 9001;
    const ERROR_LACK_OF_TOTAL = 10102;
    const ERROR_INVALID_TOTAL = 10103;
    const ERROR_NO_DAIMON_DATA = 10104;
    const ERROR_NO_CHAPTER_DATA = 10105;
    const ERROR_INVALID_PARAMETERS = 10106;
    const ERROR_INDIVIDUAL_TOTAL_MISMATCH = 10107;
    const ERROR_JSON_QUIZ_ADD_FAILED = 10201;
    const ERROR_JSON_QUIZ_GET_LAST_INSERT_ID_FAILED = 10202;
    const ERROR_JSON_QUIZ_DELETE_FAILED = 10203;
    const ERROR_JSON_QUIZ_DELETE_INVALID_PARAMETER = 10204;
    const ERROR_JSON_QUIZ_DELETE_NOT_FOUND = 10205;
    const ERROR_JSON_QUIZ_DELETE_NOT_PERMIT = 10206;
    const ERROR_JSON_QUIZ_OPTION_ADD_FAILED = 10207;
    const ERROR_JSON_QUIZ_COPY_INVALID_PARAMETER = 10208;
    const ERROR_JSON_QUIZ_FOLDER_PARAMETER_ERROR = 10209;
    const ERROR_JSON_QUIZ_FOLDER_REGISTER_FAILED = 10210;
    const ERROR_JSON_QUIZ_FOLDER_CANNOT_PARENT_OWN = 10211;
    const ERROR_JSON_QUIZ_FOLDER_CANNOT_PARENT_DESCENDANTS = 10212;
    const ERROR_JSON_QUIZ_FOLDER_DELETE_INVALID_PARAMETER = 10213;
    const ERROR_JSON_QUIZ_FOLDER_DELETE_NOT_FOUND = 10214;
    const ERROR_JSON_QUIZ_FOLDER_DELETE_NOT_PERMIT = 10215;
    const ERROR_JSON_QUIZ_FOLDER_DELETE_FAILED = 10216;
    const ERROR_JSON_QUIZ_FOLDER_DELETE_REMAIN_CHILD = 10217;
    const ERROR_JSON_QUIZ_FOLDER_MOVE_QUIZ_INVALID_PARAMETER = 10218;
    const ERROR_JSON_QUIZ_FOLDER_MOVE_QUIZ_FAILED = 10219;
    const ERROR_JSON_QUIZ_FOLDER_MOVE_NOT_PERMIT = 10220;
    const ERROR_JSON_QUIZ_FOLDER_MOVE_NOT_FOUND = 10221;
    const ERROR_JSON_QUIZ_FOLDER_BULK_MOVE_QUIZ_INVALID_PARAMETER = 10222;
    const ERROR_JSON_QUIZ_FOLDER_BULK_MOVE_QUIZ_FAILED = 10223;
    const ERROR_JSON_QUIZ_FOLDER_BULK_MOVE_NOT_PERMIT = 10224;
    const ERROR_JSON_QUIZ_FOLDER_BULK_MOVE_NOT_FOUND = 10225;
    const ERROR_JSON_QUIZ_INVALID_URL = 10301;
    const ERROR_JSON_QUIZ_PERMISSION = 10302;
    const ERROR_JSON_QUIZ_NOT_RELEASE_OR_PERMISSION = 10303;
    const ERROR_JSON_QUIZ_NO_DATA = 10304;
    const ERROR_JSON_QUIZ_NOT_DELIVERY = 10305;
    const ERROR_JSON_QUIZ_RESULT_INVALID_PARAMETER = 10401;
    const ERROR_JSON_QUIZ_RESULT_ADD_FAILED = 10402;
    const ERROR_JSON_QUIZ_RESULT_UPDATE_JSON_QUIZ = 10403;
    const ERROR_JSON_QUIZ_RESULT_UPDATE_HIGH_SCORE_FAILED = 10404;
    const ERROR_JSON_QUIZ_STUDENT_RESULT_ACCESS_ERROR = 10501;
    const ERROR_STUDENT_PASSWORD_RESET_PARAMETER_ERROR = 10601;
    const ERROR_STUDENT_PASSWORD_RESET_REGISTER_FAILED = 10602;
    const ERROR_STUDENT_DELETE_PARAMETER_ERROR = 10611;
    const ERROR_STUDENT_DELETE_FAILED = 10612;
    const ERROR_STUDENT_EDIT_INVALID_PARAMETER = 10621;
    const ERROR_STUDENT_EDIT_NO_DATA = 10622;
    const ERROR_STUDENT_EDIT_INVALID_SCHOOL = 10623;
    const ERROR_STUDENT_EDIT_UPDATE_FAILED = 10624;
    const ERROR_STUDENT_REGISTER_CODE_PARAMETER_ERROR = 10625;
    const ERROR_STUDENT_REGISTER_CODE_FAILED = 10626;
    const ERROR_STUDENT_REGISTER_CSV_PARAMETER_ERROR = 10627;
    const ERROR_STUDENT_REGISTER_CSV_FILE_NOT_FOUND = 10628;
    const ERROR_STUDENT_UPLOAD_FILE_FAILED = 10629;
    const ERROR_STUDENT_REGISTER_CSV_INVALID_FORMAT = 10630;
    const ERROR_STUDENT_REGISTER_CSV_FAILED = 10631;
    const ERROR_TEACHER_LMS_TICKET_APPLICATION_INVALID_PARAMETER = 10701;
    const ERROR_TEACHER_LMS_TICKET_APPLICATION_INVALID_QUANTITY = 10702;
    const ERROR_TEACHER_LMS_TICKET_APPLICATION_ADD_FAILED = 10703;
    const ERROR_TEACHER_LMS_TICKET_APPLICATION_ALREADY_ADD = 10704;
    const ERROR_TEACHER_LMS_TICKET_APPLICATION_OUTDATED = 10705;
    const ERROR_TEACHER_LMS_TICKET_APPLICATION_DATA_IS_NONE = 10706;
    const ERROR_TEACHER_LMS_TICKET_APPLICATION_NOT_PERMIT = 10707;
    const ERROR_TEACHER_LMS_TICKET_APPLICATION_DELETE_FAILED = 10708;
    const ERROR_TEACHER_LMS_TICKET_APPLICATION_DELETE_INVALID_PARAMETER = 10709;
    const ERROR_TEACHER_LMS_TICKET_GROUP_INVALID_PARAMETER = 10710;
    const ERROR_TEACHER_LMS_TICKET_GROUP_INVALID_QUANTITY = 10711;
    const ERROR_TEACHER_LMS_TICKET_GROUP_QUANTITY_NOT_ENOUGH = 10712;
    const ERROR_TEACHER_LMS_TICKET_GROUP_USE_COUNT_OVER = 10713;
    const ERROR_TEACHER_LMS_TICKET_GROUP_EMPTY_NAME = 10714;
    const ERROR_TEACHER_LMS_TICKET_GROUP_ADD_FAILED = 10715;
    const ERROR_TEACHER_LMS_TICKET_GROUP_NOT_ENOUGH = 10716;
    const ERROR_TEACHER_LMS_TICKET_GROUP_DATA_IS_NONE = 10717;
    const ERROR_TEACHER_LMS_TICKET_GROUP_NOT_PERMIT = 10718;
    const ERROR_TEACHER_LMS_TICKET_GROUP_DELETE_FAILED = 10719;
    const ERROR_TEACHER_LMS_TICKET_DATA_IS_NONE = 10720;
    const ERROR_TEACHER_LMS_TICKET_NOT_PERMIT = 10721;
    const ERROR_TEACHER_LMS_TICKET_DELETE_FAILED = 10722;
    const ERROR_TEACHER_LMS_TICKET_DELETE_INVALID_PARAMETER = 10723;
    const ERROR_TEACHER_LMS_TICKET_USER_GET_INVALID_PARAMETER = 10724;
    const ERROR_TEACHER_LMS_TICKET_USER_DELETE_INVALID_PARAMETER = 10725;
    const ERROR_TEACHER_REGISTER_INVALID_PARAMETERS = 19001;
    const ERROR_STUDENT_ACCESS_NOT_LOGIN = 20001;
    const ERROR_STUDENT_ACCESS_INVALID_PARAMETER = 20002;
    const ERROR_STUDENT_ACCESS_TOKEN_NOT_FOUND = 20003;
    const ERROR_STUDENT_REGISTER_INVALID_PARAMETER = 20011;
    const ERROR_STUDENT_REGISTER_FAILED = 20012;
    const ERROR_STUDENT_REGISTER_FAILED_SCHOOL = 20013;
    const ERROR_STUDENT_REGISTER_FAILED_AUTHORIZATION_KEY = 20014;
    const ERROR_STUDENT_REGISTER_FAILED_STUDENT_ID = 20015;
    const ERROR_STUDENT_REGISTER_FAILED_LMS_CODE = 20016;
    const ERROR_STUDENT_REGISTER_FOR_WEB_FAILED_ILLEGAL_TRANSITION = 20031;
    const ERROR_STUDENT_REGISTER_FOR_WEB_FAILED_LOGIN_ID_NULL = 20032;
    const ERROR_STUDENT_REGISTER_FOR_WEB_FAILED_LOGIN_ID_ALREADY_REGISTERED = 20033;
    const ERROR_STUDENT_REGISTER_FOR_WEB_FAILED_LOGIN_ID_INVALID = 20034;
    const ERROR_STUDENT_REGISTER_FOR_WEB_FAILED_PASSWORD_NULL = 20035;
    const ERROR_STUDENT_REGISTER_FOR_WEB_FAILED_PASSWORD_INVALID = 20036;
    const ERROR_STUDENT_REGISTER_FOR_WEB_FAILED_PASSWORD_NOT_SAME = 20037;
    const ERROR_STUDENT_REGISTER_FOR_WEB_FAILED_NAME_NULL = 20038;
    const ERROR_STUDENT_REGISTER_FOR_WEB_FAILED_LMS_CODE_NULL = 20039;
    const ERROR_STUDENT_REGISTER_FOR_WEB_FAILED_LMS_CODE_INVALID = 20040;
    const ERROR_STUDENT_REGISTER_FOR_WEB_FAILED_LMS_CODE_ALREADY_REGISTERED = 20041;
    const ERROR_STUDENT_REGISTER_FOR_WEB_FAILED_STUDENT_NUMBER_NULL = 20042;
    const ERROR_STUDENT_AUTHORIZATION_INVALID_PARAMETER = 20101;
    const ERROR_STUDENT_AUTHORIZATION_NOT_FOUND = 20102;
    const ERROR_STUDENT_AUTHORIZATION_FAILED = 20103;
    const ERROR_STUDENT_ACCESS_TOKEN_GENERATE_INVALID_PARAMETER = 20111;
    const ERROR_STUDENT_ACCESS_TOKEN_GENERATE_REFRESH_TOKEN_NOT_FOUND = 20112;
    const ERROR_STUDENT_ACCESS_TOKEN_GENERATE_FAILED = 20113;
    const ERROR_STUDENT_REFRESH_TOKEN_GENERATE_INVALID_PARAMETER = 20116;
    const ERROR_STUDENT_REFRESH_TOKEN_GENERATE_FAILED = 20117;
    const ERROR_STUDENT_LOGIN_TOKEN_GENERATE_FAILED = 20121;
    const ERROR_STUDENT_LOGIN_INVALID_PARAMETER = 20131;
    const ERROR_STUDENT_LOGIN_TOKEN_NOT_FOUND = 20132;
    const ERROR_STUDENT_LOGIN_STUDENT_NOT_FOUND = 20133;
    const ERROR_STUDENT_LOGIN_FAILED = 20134;
    const ERROR_STUDENT_AUTO_LOGIN_INVALID_PARAMETER = 20141;
    const ERROR_STUDENT_AUTO_LOGIN_TOKEN_NOT_FOUND = 20142;
    const ERROR_STUDENT_AUTO_LOGIN_STUDENT_NOT_FOUND = 20143;
    const ERROR_STUDENT_CHANGE_PASSWORD_FAILED = 20151;
    const ERROR_STUDENT_ADD_LMS_CODE = 20152;
    const ERROR_STUDENT_CHANGE_PROFILE_FAILED = 20161;
    const ERROR_STUDENT_ADD_FCM_TOKEN_FAILED = 20171;
    const ERROR_STUDENT_UPDATE_FCM_TOKEN_FAILED = 20172;
    const ERROR_STUDENT_ONIGIRI_JSON_QUIZ_NOT_DELIVERY = 20201;
    const ERROR_STUDENT_ONIGIRI_JSON_QUIZ_NOT_FOUND = 20202;
    const ERROR_EBOOK_MODE_UNKNOWN = 30001;
    const ERROR_EBOOK_FLASH_CARD_INVALID_PARAMETER = 30201;
    const ERROR_EBOOK_FLASH_CARD_NO_DATA = 30202;
    const ERROR_EBOOK_FLASH_CARD_NOT_ENOUGH = 30203;
    const ERROR_EBOOK_INFORMATION_INVALID_PARAMETER = 30301;
    const ERROR_EBOOK_INFORMATION_NO_DATA = 30302;
    const ERROR_EBOOK_VOICE_INVALID_PARAMETER = 30401;
    const ERROR_EBOOK_VOICE_NO_DATA = 30402;
    const ERROR_EBOOK_QUIZ_INVALID_PARAMETER = 30501;
    const ERROR_EBOOK_QUIZ_NO_DATA = 30502;
    const ERROR_EBOOK_QUIZ_NOT_ENOUGH = 30503;
    const ERROR_EBOOK_SCHOOL_INVALID_PARAMETER = 30601;
    const ERROR_EBOOK_SCHOOL_INVALID_LMS_CODE = 30602;
    const ERROR_ADMIN_NOT_LOGIN = 80000;
    const ERROR_ADMIN_LMS_CODE_APPLICATION_INVALID_PARAMETER = 80101;
    const ERROR_ADMIN_LMS_CODE_APPLICATION_NO_DATA = 80102;
    const ERROR_ADMIN_LMS_CODE_APPLICATION_REGISTER_FAILED = 80103;
    const ERROR_ADMIN_BOOK_APPLICATION_PARAMETER_ERROR = 80201;
    const ERROR_ADMIN_BOOK_APPLICATION_REGISTER_FAILED = 80202;
    const ERROR_ADMIN_BOOK_APPLICATION_ALREADY_REGISTERED = 80203;
    const ERROR_ADMIN_BOOK_APPLICATION_DELETE_FAILED = 80204;
    const ERROR_ADMIN_LMS_TICKET_APPLICATION_INVALID_PARAMETER = 80301;
    const ERROR_ADMIN_LMS_TICKET_APPLICATION_REGISTER_FAILED = 80302;
    const ERROR_ADMIN_LMS_TICKET_APPLICATION_UPDATE_FAILED = 80303;
    const ERROR_ADMIN_LMS_TICKET_APPLICATION_ALREADY_DELETED = 80304;
    const ERROR_ADMIN_LMS_TICKET_APPLICATION_NO_DATA = 80305;
    const ERROR_DB_UNKNOWN = 90001;
    const ERROR_COMMON_ILLEGAL_TRANSITION = 90101;
    const ERROR_COMMON_NOT_LOGINED = 90102;
    const ERROR_UNKNOWN = 99999;

    public static function ShowErrorJson($errorCode)
    {
        http_response_code(400);

        $message = ErrorMessage::GetMessage($errorCode);
        $result = [
            'error' => [
                'code' => $errorCode,
                'message' => $message
            ]
        ];

        error_log("$message (code: $errorCode)");
        DisplayJsonHelper::ShowAndExit($result);
        exit;
    }

    public static function GetErrorResultData($errorCode)
    {
        return [
            'error' => [
                'code' => $errorCode,
                'message' => ErrorMessage::GetMessage($errorCode)
            ]
        ];
    }
}